spring.application.name=booknest-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/booknestdb
spring.datasource.username=booknestuser
spring.datasource.password=booknestpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=false


/* token imzalamak için gizli anahtar */
jwt.secret=bXktc3VwZXItc2VjcmV0LWtleS1mb3ItYm9va25lc3Qtand0LTEyMzQ1Njc4OTAxMg==

/* token kaç milisaniye geçerli olacak Şimdilik local geliştirme için bunu kullanıyoruz.
 Gerçek projede bu secret değerini doğrudan dosyaya yazmak yerine environment variable ile saklarız. */
jwt.expiration-ms=86400000